# Generated by Django 5.0.1 on 2025-11-21 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faixa_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_em_reais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faixa de Bônus',
                'verbose_name_plural': 'Faixas de Bônus',
                'ordering': ['faixa_min'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoExpedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_expedicao', models.CharField(choices=[('motoboy', 'Motoboy'), ('sedex', 'Sedex')], max_length=20, unique=True)),
                ('pontos_por_rota_motoboy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pontos_fixos_diarios_motoboy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_pontuacao_sedex', models.CharField(choices=[('por_envio', 'Por Envio'), ('por_dia', 'Por Dia')], default='por_envio', max_length=20)),
                ('pontos_sedex', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Expedição',
                'verbose_name_plural': 'Configurações de Expedição',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sequencia', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
                ('se_gera_pontos', models.BooleanField(default=True)),
                ('se_possui_checklists', models.BooleanField(default=False)),
                ('se_possui_calculo_por_quantidade', models.BooleanField(default=False)),
                ('grupo', models.CharField(choices=[('triagem', 'Triagem'), ('producao', 'Produção'), ('conf_rotulagem', 'Conf/Rotulagem'), ('expedicao', 'Expedição')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['sequencia'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('capsula_sache', 'Laboratório de Cápsulas e Sachês'), ('pediatrico', 'Laboratório Pediátrico'), ('externo', 'Laboratório Externo')], max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laboratório',
                'verbose_name_plural': 'Laboratórios',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_fixos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pontos_por_check', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pontos_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pontos_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('versao', models.CharField(default='1.0', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_pontuacao', to='core.etapa')),
            ],
            options={
                'verbose_name': 'Configuração de Pontuação',
                'verbose_name_plural': 'Configurações de Pontuação',
                'ordering': ['-versao'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('pontos_do_check', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('tipo_contagem_sedex', models.CharField(blank=True, choices=[('por_dia', 'Por Dia'), ('por_rota', 'Por Rota')], default='por_dia', max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.etapa')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_fim', models.DateTimeField(blank=True, null=True)),
                ('quantidade_produzida', models.IntegerField(default=0)),
                ('pontos_gerados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etapa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('versao_configuracao_pontuacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.configuracaopontuacao')),
            ],
            options={
                'verbose_name': 'Histórico de Etapa',
                'verbose_name_plural': 'Histórico de Etapas',
                'ordering': ['-timestamp_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.BooleanField(default=False)),
                ('pontos_gerados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marcado_em', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checklist')),
                ('historico_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_executados', to='core.historicoetapa')),
            ],
            options={
                'verbose_name': 'Execução de Checklist',
                'verbose_name_plural': 'Execuções de Checklists',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('assumir_etapa', 'Assumir Etapa'), ('concluir_etapa', 'Concluir Etapa'), ('marcar_check', 'Marcar Checklist'), ('alterar_regra', 'Alterar Regra'), ('penalizacao', 'Penalização'), ('reverter_penalizacao', 'Reverter Penalização'), ('aprovar_pedido', 'Aprovar Pedido'), ('reprovar_pedido', 'Reprovar Pedido'), ('criar_etapa', 'Criar Etapa'), ('editar_etapa', 'Editar Etapa'), ('criar_usuario', 'Criar Usuário'), ('editar_usuario', 'Editar Usuário'), ('outros', 'Outros')], max_length=50)),
                ('descricao', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('dados_adicionais', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('codigo_pedido', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('em_fluxo', 'Em Fluxo'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_fluxo', max_length=30)),
                ('informacoes_gerais', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('etapa_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_na_etapa', to='core.etapa')),
                ('funcionario_na_etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_assumidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='historicoetapa',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='core.pedido'),
        ),
        migrations.CreateModel(
            name='Penalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=500)),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.TextField()),
                ('revertida', models.BooleanField(default=False)),
                ('revertida_em', models.DateTimeField(blank=True, null=True)),
                ('aplicada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizacoes_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizacoes', to=settings.AUTH_USER_MODEL)),
                ('revertida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalizacoes_revertidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penalização',
                'verbose_name_plural': 'Penalizações',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PontuacaoFixaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regra', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('tipo_aplicacao', models.CharField(choices=[('automatica', 'Automática'), ('manual_gerente', 'Manual pelo Gerente')], max_length=20)),
                ('condicao_aplicacao', models.TextField(blank=True, help_text='Condição para aplicação automática')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacoes_fixas', to='core.etapa')),
            ],
            options={
                'verbose_name': 'Pontuação Fixa Mensal',
                'verbose_name_plural': 'Pontuações Fixas Mensais',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAplicacaoPontuacaoFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('pontos_aplicados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aplicado_em', models.DateTimeField(auto_now_add=True)),
                ('justificativa', models.TextField(blank=True)),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacoes_fixas_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes_fixas_recebidas', to=settings.AUTH_USER_MODEL)),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_aplicacoes', to='core.pontuacaofixamensal')),
            ],
            options={
                'verbose_name': 'Histórico de Aplicação de Pontuação Fixa',
                'verbose_name_plural': 'Histórico de Aplicações de Pontuação Fixa',
                'ordering': ['-aplicado_em'],
            },
        ),
        migrations.CreateModel(
            name='PontuacaoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origem', models.CharField(choices=[('etapa', 'Etapa'), ('producao', 'Produção'), ('check', 'Checklist'), ('penalizacao', 'Penalização'), ('expedicao', 'Expedição'), ('mensal', 'Bonificação Mensal')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mes_referencia', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.etapa')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'verbose_name': 'Pontuação do Funcionário',
                'verbose_name_plural': 'Pontuações dos Funcionários',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegistroExpedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pontos_gerados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configuracaoexpedicao')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedicoes', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'verbose_name': 'Registro de Expedição',
                'verbose_name_plural': 'Registros de Expedição',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RegraProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa_min', models.IntegerField()),
                ('faixa_max', models.IntegerField()),
                ('pontos_por_unidade', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pontos_fixos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('versao', models.CharField(default='1.0', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_producao', to='core.etapa')),
            ],
            options={
                'verbose_name': 'Regra de Produção',
                'verbose_name_plural': 'Regras de Produção',
                'ordering': ['faixa_min'],
            },
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('capsula', 'Cápsula'), ('sache', 'Sachê'), ('liquido_pediatrico', 'Líquido Pediátrico'), ('lotion', 'Loção'), ('creme', 'Creme'), ('shampoo', 'Shampoo'), ('shot', 'Shot'), ('ovulo', 'Óvulo'), ('comprimido_sublingual', 'Comprimido Sublingual'), ('capsula_oleosa', 'Cápsula Oleosa'), ('goma', 'Goma'), ('chocolate', 'Chocolate'), ('filme', 'Filme')], max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_produtos', to='core.laboratorio')),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produto',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='core.tipoproduto'),
        ),
        migrations.CreateModel(
            name='HistoricoBonusMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('pontos_totais_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_em_reais_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('timestamp_calculo', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_mensais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Bônus Mensal',
                'verbose_name_plural': 'Histórico de Bônus Mensais',
                'ordering': ['-mes_referencia', '-pontos_totais_mes'],
                'unique_together': {('mes_referencia', 'funcionario')},
            },
        ),
        migrations.CreateModel(
            name='PontuacaoPorAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(choices=[('pesagem', 'Pesagem'), ('encapsulacao', 'Encapsulação'), ('analise', 'Análise'), ('rotulagem', 'Rotulagem'), ('conferencia', 'Conferência'), ('reconferencia', 'Reconferência')], max_length=50)),
                ('faixa_min', models.IntegerField()),
                ('faixa_max', models.IntegerField()),
                ('pontos_por_formula', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes_atividade', to='core.etapa')),
                ('tipo_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='core.tipoproduto')),
            ],
            options={
                'verbose_name': 'Pontuação por Atividade',
                'verbose_name_plural': 'Pontuações por Atividade',
                'ordering': ['etapa', 'tipo_produto', 'atividade', 'faixa_min'],
                'unique_together': {('etapa', 'tipo_produto', 'atividade', 'faixa_min', 'faixa_max')},
            },
        ),
    ]
