# Generated by Django 5.0.1 on 2025-12-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_atualizacao_api',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descricao_web',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_api',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_pedido_api',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_pedido_web',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='price_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_identificado',
            field=models.CharField(default='desconhecido', help_text='Tipo identificado automaticamente da descrição (desconhecido = requer ajuste manual)', max_length=50),
        ),
    ]
