# Generated by Django 5.0.1 on 2025-12-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_data_atualizacao_api_pedido_descricao_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido_api',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_pedido_web',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
