# Generated by Django 5.0.1 on 2025-12-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pedido_codigo_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_atualizacao_api', '-hora_atualizacao_api'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='hora_atualizacao_api',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
