# Generated by Django 5.0.1 on 2025-12-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_checklist_tipo_contagem_sedex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='pontos_fixos_etapa',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pontos adicionados ao concluir a etapa (além dos checklists, se houver)', max_digits=10),
        ),
    ]
