# Generated by Django 5.0.1 on 2025-12-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_etapa_pontos_fixos_etapa'),
        ('core', '0008_pedido_status_fila'),
    ]

    operations = [
    ]
