# Generated by Django 5.0.1 on 2025-12-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20251223_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_expedicao',
            field=models.CharField(blank=True, choices=[('motoboy', 'Motoboy'), ('sedex', 'Sedex')], help_text='Tipo de expedição selecionado pelo funcionário', max_length=20, null=True),
        ),
    ]
