# Generated by Django 5.0.1 on 2025-12-23 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pedido_tipo_expedicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlePergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(help_text='Ex: Conferiu os produtos?', max_length=500)),
                ('tipo_campo', models.CharField(choices=[('texto', 'Texto Simples'), ('textarea', 'Texto Longo'), ('checkbox', 'Sim/Não'), ('selecao', 'Seleção Múltipla'), ('numero', 'Número')], default='texto', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição adicional ou instruções')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de apresentação das perguntas')),
                ('obrigatorio', models.BooleanField(default=True, help_text='Se a resposta é obrigatória')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_controle_qualidade', to='core.etapa')),
            ],
            options={
                'verbose_name': 'Pergunta de Controle de Qualidade',
                'verbose_name_plural': 'Perguntas de Controle de Qualidade',
                'ordering': ['ordem', 'id'],
                'unique_together': {('etapa', 'pergunta')},
            },
        ),
        migrations.CreateModel(
            name='ControlePerguntaOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcao', models.CharField(max_length=200)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='core.controlepergunta')),
            ],
            options={
                'verbose_name': 'Opção de Pergunta',
                'verbose_name_plural': 'Opções de Pergunta',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoControleQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preenchido_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_controle_qualidade', to=settings.AUTH_USER_MODEL)),
                ('historico_etapa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controle_qualidade', to='core.historicoetapa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_controle_qualidade', to='core.pedido')),
            ],
            options={
                'verbose_name': 'Histórico de Controle de Qualidade',
                'verbose_name_plural': 'Histórico de Controles de Qualidade',
                'ordering': ['-preenchido_em'],
            },
        ),
        migrations.CreateModel(
            name='RespostaControleQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(blank=True, help_text='Para respostas de texto ou textarea')),
                ('preenchido_em', models.DateTimeField(auto_now_add=True)),
                ('historico_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.historicocontrolequalidade')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.controlepergunta')),
                ('resposta_opcao', models.ForeignKey(blank=True, help_text='Para respostas de checkbox ou seleção', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.controleperguntaopcao')),
            ],
            options={
                'verbose_name': 'Resposta de Controle de Qualidade',
                'verbose_name_plural': 'Respostas de Controle de Qualidade',
                'ordering': ['pergunta__ordem', 'pergunta__id'],
                'unique_together': {('historico_controle', 'pergunta')},
            },
        ),
    ]
