# Generated by Django 5.0.1 on 2025-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_controlepergunta_controleperguntaopcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nrorc',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
