# Generated by Django 5.0.1 on 2025-12-24 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pedido_nrorc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicocontrolequalidade',
            options={'ordering': ['-preenchido_em'], 'verbose_name': 'Formulário de Controle de Qualidade', 'verbose_name_plural': 'Formulários de Controle de Qualidade'},
        ),
        migrations.AlterUniqueTogether(
            name='controlepergunta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicocontrolequalidade',
            name='historico_etapa',
        ),
        migrations.RemoveField(
            model_name='historicocontrolequalidade',
            name='pedido',
        ),
        migrations.AddField(
            model_name='controlepergunta',
            name='pontuacao_pergunta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pontuação agregada a esta pergunta', max_digits=5),
        ),
        migrations.AddField(
            model_name='historicocontrolequalidade',
            name='codigo_item',
            field=models.CharField(blank=True, help_text='Código do item (opcional)', max_length=100),
        ),
        migrations.AddField(
            model_name='historicocontrolequalidade',
            name='id_controle',
            field=models.CharField(blank=True, help_text='ID ou referência do item (preenchido pelo funcionário)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicocontrolequalidade',
            name='nome_item',
            field=models.CharField(blank=True, help_text='Nome do item/produto sendo inspecionado', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicocontrolequalidade',
            name='pontuacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pontuação obtida no formulário', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historicocontrolequalidade',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_controle_qualidade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='controlepergunta',
            name='etapa',
        ),
    ]
