# Generated by Django 5.0.1 on 2025-12-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_historicocontrolequalidade_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoControleQualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_configuracao', models.CharField(default='Padrão', max_length=200, unique=True)),
                ('pontos_por_formulario', models.DecimalField(decimal_places=2, default=5, help_text='Pontuação atribuída cada vez que um formulário de CQ é preenchido', max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da configuração')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Controle de Qualidade',
                'verbose_name_plural': 'Configurações de Controle de Qualidade',
            },
        ),
    ]
