# Generated by Django 5.0.1 on 2025-12-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuracaocontrolequalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaofuncionario',
            name='origem',
            field=models.CharField(choices=[('etapa', 'Etapa'), ('producao', 'Produção'), ('check', 'Checklist'), ('penalizacao', 'Penalização'), ('expedicao', 'Expedição'), ('mensal', 'Bonificação Mensal'), ('controle_qualidade', 'Controle de Qualidade')], max_length=20),
        ),
    ]
