# Generated by Django 5.0.1 on 2025-12-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_pontuacaofuncionario_origem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlepergunta',
            name='pontuacao_pergunta',
        ),
    ]
