# Generated by Django 5.0.1 on 2026-03-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_update_pedido_add_api_config_agendamentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoMestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrorc', models.BigIntegerField(db_index=True, help_text='Número RC do pedido (identificador único da API)', unique=True)),
                ('status', models.CharField(choices=[('em_processamento', 'Em Processamento'), ('pronto_para_expedicao', 'Pronto para Expedição'), ('parcialmente_concluido', 'Parcialmente Concluído'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_processamento', max_length=30)),
                ('cliente', models.CharField(blank=True, help_text='Nome do cliente', max_length=200)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido Mestre',
                'verbose_name_plural': 'Pedidos Mestres',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FormulaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição da fórmula (ex: VITAMINA A + D3 + TCM | 10ML)')),
                ('quantidade', models.IntegerField(default=1, help_text='Quantidade de unidades')),
                ('volume_ml', models.CharField(blank=True, help_text='Volume em ML se aplicável (ex: 10ML, 60ML)', max_length=20)),
                ('id_api', models.CharField(db_index=True, help_text='ID único da fórmula vindo da API', max_length=100, unique=True)),
                ('serieo', models.CharField(blank=True, help_text='Série do item (SERIEO)', max_length=20)),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Preço unitário', max_digits=15, null=True)),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, help_text='Preço total', max_digits=15, null=True)),
                ('status', models.CharField(choices=[('em_triagem', 'Em Triagem'), ('em_producao', 'Em Produção'), ('em_qualidade', 'Em Qualidade'), ('pronto_para_expedicao', 'Pronto para Expedição'), ('expedido', 'Expedido'), ('cancelado', 'Cancelado')], default='em_triagem', max_length=30)),
                ('data_criacao_api', models.DateField(blank=True, help_text='Data de criação no sistema da API', null=True)),
                ('data_atualizacao_api', models.DateField(blank=True, help_text='Data de atualização no sistema da API', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('etapa_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etapa')),
                ('funcionario_na_etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulas_assumidas', to=settings.AUTH_USER_MODEL)),
                ('pedido_mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='core.pedidomestre')),
            ],
            options={
                'verbose_name': 'Item de Fórmula',
                'verbose_name_plural': 'Itens de Fórmula',
                'ordering': ['pedido_mestre', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEtapaFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_fim', models.DateTimeField(blank=True, null=True)),
                ('pontos_gerados', models.DecimalField(decimal_places=2, default=0, help_text='Pontos ganhos nesta etapa', max_digits=10)),
                ('rota_tipo', models.CharField(blank=True, choices=[('motoboy', 'Motoboy'), ('sedex', 'Sedex')], help_text='Tipo de rota (apenas preenchido na Expedição)', max_length=20, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etapa')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_etapas', to='core.formulaitem')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Etapa da Fórmula',
                'verbose_name_plural': 'Históricos de Etapas das Fórmulas',
                'ordering': ['-timestamp_inicio'],
            },
        ),
    ]
