# Generated by Django 5.0.1 on 2026-03-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_pedidomestre_formulaitem_historicoetapaformula'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistExecucaoFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.BooleanField(default=False)),
                ('pontos_gerados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('marcado_em', models.DateTimeField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.checklist')),
                ('historico_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_executados', to='core.historicoetapaformula')),
            ],
            options={
                'verbose_name': 'Execução de Checklist de Fórmula',
                'verbose_name_plural': 'Execuções de Checklists de Fórmulas',
                'unique_together': {('historico_etapa', 'checklist')},
            },
        ),
    ]
