# Generated by Django 5.0.1 on 2026-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_checklistexecucaoformula'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaitem',
            name='eh_tarefa_ativa',
            field=models.BooleanField(default=False, help_text='Indica se é a tarefa ativa do funcionário nesta etapa'),
        ),
    ]
