# Generated by Django 5.0.1 on 2026-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_tarefa_ativa_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidomestre',
            name='status',
            field=models.CharField(choices=[('em_processamento', 'Em Processamento'), ('pronto_para_expedicao', 'Pronto para Expedição'), ('em_rota_motoboy', 'Em Rota Motoboy'), ('em_rota_sedex', 'Em Rota Sedex'), ('expedido', 'Expedido'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='em_processamento', max_length=30),
        ),
    ]
