# Generated by Django 5.0.1 on 2026-03-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_update_pedido_mestre_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroexpedicao',
            name='pedidos_mestre',
            field=models.ManyToManyField(blank=True, related_name='registros_expedicao', to='core.pedidomestre'),
        ),
        migrations.AddField(
            model_name='registroexpedicao',
            name='rota_tipo',
            field=models.CharField(blank=True, choices=[('motoboy', 'Motoboy'), ('sedex', 'Sedex')], max_length=20),
        ),
        migrations.AddField(
            model_name='registroexpedicao',
            name='total_formulas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroexpedicao',
            name='total_pedidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registroexpedicao',
            name='configuracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.configuracaoexpedicao'),
        ),
        migrations.AlterField(
            model_name='registroexpedicao',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registroexpedicao',
            name='pontos_gerados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
