# Generated by Django 5.0.1 on 2026-03-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_update_registro_expedicao_pedidosmestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoaplicacaopontuacaofixa',
            name='aplicado_por',
        ),
        migrations.RemoveField(
            model_name='historicoaplicacaopontuacaofixa',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='historicoaplicacaopontuacaofixa',
            name='regra',
        ),
        migrations.RemoveField(
            model_name='historicoetapa',
            name='etapa',
        ),
        migrations.RemoveField(
            model_name='historicoetapa',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='historicoetapa',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='historicoetapa',
            name='versao_configuracao_pontuacao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='etapa_atual',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='funcionario_na_etapa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='pontuacaofuncionario',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='registroexpedicao',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='regraproducao',
            name='etapa',
        ),
        migrations.DeleteModel(
            name='ChecklistExecucao',
        ),
        migrations.DeleteModel(
            name='HistoricoAplicacaoPontuacaoFixa',
        ),
        migrations.DeleteModel(
            name='HistoricoEtapa',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='RegraProducao',
        ),
    ]
