# Generated by Django 5.0.1 on 2026-03-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_historicoaplicacaopontuacaofixa_aplicado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidomestre',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='formulaitem',
            name='datetime_atualizacao_api',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Data + Hora de atualização na API (DTALT + HRALT)', null=True),
        ),
    ]
