# Generated by Django 5.0.1 on 2026-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_pedidomestre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoexpedicao',
            name='tipo_expedicao',
            field=models.CharField(choices=[('motoboy', 'Motoboy'), ('sedex', 'Sedex'), ('retirada', 'Retirada')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registroexpedicao',
            name='rota_tipo',
            field=models.CharField(blank=True, choices=[('motoboy', 'Motoboy'), ('sedex', 'Sedex'), ('retirada', 'Retirada')], max_length=20),
        ),
    ]
