# Generated by Django 5.0.1 on 2026-04-01 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_configuracaoexpedicao_tipo_expedicao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegacaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_delegacao', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True, help_text='Se a delegação está ativa')),
                ('data_conclusao', models.DateTimeField(blank=True, help_text='Quando a tarefa foi concluída', null=True)),
                ('delegado_para', models.ForeignKey(help_text='Funcionário que recebeu a tarefa', on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('delegado_por', models.ForeignKey(blank=True, help_text='Funcionário que delegou a tarefa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etapa')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegacoes', to='core.formulaitem')),
            ],
            options={
                'verbose_name': 'Delegação de Tarefa',
                'verbose_name_plural': 'Delegações de Tarefas',
                'ordering': ['-data_delegacao'],
            },
        ),
    ]
