# Generated by Django 5.0.1 on 2026-04-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delegacaotarefa'),
    ]

    operations = [
    ]
